require 'pry'
require 'nokogiri'
require 'open-uri'

# Add all required files here -> require_relative '../lib/files'
require_relative '../lib/bestfriendfinder'
require_relative '../lib/bestfriendfinder/cli'
require_relative '../lib/bestfriendfinder/scraper'
require_relative '../lib/bestfriendfinder/animalfactory'
require_relative '../lib/bestfriendfinder/animals'
require_relative '../lib/bestfriendfinder/animals/dogs'
require_relative '../lib/bestfriendfinder/animals/cats'
require_relative '../lib/bestfriendfinder/animals/rabbits'
